/*********************************************************************
 * Name:      	main.h
 * Purpose:   	Declares simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:
 * Created:
 * Copyright:
 * License:   	wxWidgets license (www.wxwidgets.org)
 *
 * Notes:		Note that all GUI creation code is declared in
 * 				gui.h source file which is generated by wxFormBuilder.
 *********************************************************************/

#ifndef __main__
#define __main__

// main wxWidgets header file
#include <wx/wx.h>
// gui classes generated by wxFormBuilder
#include "gui.h"

////////////////////////////////////////////////////////////////////////////////
// application class declaration
////////////////////////////////////////////////////////////////////////////////

class MainApp : public wxApp
{
public:
	virtual bool OnInit();
};

// declare global static function wxGetApp()
DECLARE_APP(MainApp)

////////////////////////////////////////////////////////////////////////////////
// main application frame declaration
////////////////////////////////////////////////////////////////////////////////

class MainDialog : public MainDialogBase
{
public:
	MainDialog( wxWindow *parent );
	virtual ~MainDialog();

protected:
	// protected event handlers
	virtual void OnCloseDialog( wxCloseEvent& event );
	virtual void OnOKClick( wxCommandEvent& event );
	virtual void OnCancelClick( wxCommandEvent& event );

	/**
	 * @brief
	 * @param event
	 */
	virtual void onToggleButton1(wxCommandEvent& event);
	/**
	 * @brief
	 * @param event
	 */
	virtual void onToggleButton2(wxCommandEvent& event);
	/**
	 * @brief
	 * @param event
	 */
	virtual void onToggleButton3(wxCommandEvent& event);
	/**
	 * @brief
	 * @param event
	 */
	virtual void onToggleButton4(wxCommandEvent& event);
	/**
	 * @brief
	 * @param event
	 */
	virtual void onToggleButton5(wxCommandEvent& event);
	/**
	 * @brief
	 * @param event
	 */
	virtual void onToggleButton6(wxCommandEvent& event);
	/**
	 * @brief
	 * @param event
	 */
	virtual void onToggleButton7(wxCommandEvent& event);

	/**
	 * @brief
	 * @param event
	 */
	virtual void OnButtonClick(wxCommandEvent& event);
	/**
	 * @brief
	 * @param event
	 */
	void onToggleButton10(wxCommandEvent& event);
	/**
	 * @brief
	 * @param event
	 */
	void onToggleButton11(wxCommandEvent& event);
	/**
	 * @brief
	 * @param event
	 */
	void onToggleButton12(wxCommandEvent& event);
	/**
	 * @brief
	 * @param event
	 */
	void onToggleButton8(wxCommandEvent& event);
	/**
	 * @brief
	 * @param event
	 */
	void onToggleButton9(wxCommandEvent& event);

private:
	typedef struct
	{
		TCHAR desc[MAX_PATH];
		TCHAR filename[MAX_PATH];
	} T_LINE;
	T_LINE lines[12];
};

#endif //__main__
